name: Export and Unpack Solution

on:
  push:
    branches:
      - main

jobs:
  export-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ secrets.https://org682aa468.crm8.dynamics.com/ }}
          solution-name: 'test'
          solution-output-file: 'solution.zip'

      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: 'test23_1_0_0_1.zip'
          target-folder: 'SolutionFolder'
